# 46장 제너레이터와 async/await

## 46.1 제너레이터란?

ES6에서 도입된 제너레이터는 코드 블록의 실행을 일시 중지했다가 필요한 시점에 재개할 수 있는 특수한 함수이다.  
<제너레이터와 일반 함수의 차이>

1. 제너레이터 함수는 함수 호출자에게 함수 실행의 제어권을 양도할 수 있다.
2. 제너레이터 함수는 함수 호출자와 함수의 상태를 주고받을 수 있다.
3. 제너레이터 함수를 호출하면 제너레이터 객체를 반환한다.  
   (제너레이터 함수를 호출하면 함수 코드를 실행하는 것이 아니라 이터러블이면서 동시에 이터레이터인 제너레이터 객체를 반환한다.)

<br/>

## 46.2 제너레이터 함수의 정의

제너레이터 함수는 `function*` 키워드로 선언한다. 그리고 하나 이상의 `yield `표현식을 포함한다.

```
//제너레이터 함수 선언문
function* getDenFunc(){
    yield 1;
}

// 함수 표현식
const getExpFunc = function* (){
    yield 1;
}

//메서드
const obj = {
    * getObjMethod(){
        yield 1;
    }
};

//클래스 메서드
class MyClass {
    *getClsMethod(){
        yield 1;
    }
}
```

제너레이터 함수는 `화살표 함수`와 `new 연산자와 함께 생성자 함수`로 호출할 수 없다.

<br/>

## 46.3 제너레이터 객체

**제너레이터 함수를 호출하면 일반 함수처럼 함수 코드 블록을 실행하는 것이 아니라 제너레이터 객체를 생성해 반환한다. 제너레이터 함수가 반환한 제너레이터 객체는 이터러블이면서 동시에 이터레이터이다.**  
다시 말해, 제너레이터 객체는 `Symbol.iterator` 메서드를 상속받는 이터러블이면서 `value, done` 프로퍼티를 갖는 이터레이터 리절트 객체를 반환하는 `next 메서드` 소유하는 이터레이터이다.  
<br/>

제너레이터 객체는 `next` 메서드를 갖는 이터레이터이지만 이터레이터에 없는 `return, throw` 메서드를 갖는다.

```
function* getFunc(){
    try{
        yield 1;
        yield 2;
        yield 3;
    }catch(e){
        console.error(e);
    }
}
const generator = genFunc();

console.log(generator.next()); {value :1, done :false}
console.log(generator.return('End!')); //{value:'End!',done:true}
```

- next 메서드를 호출하면 제너레이터 함수의 yield 표현식까지 코드 블록을 실행하고 yield된 값을 value 프로퍼티 값으로, false를 done 프로퍼티 값으로 갖는 이터레이터 리절트 객체를 반환한다.
- 만약 `throw메서드`를 호출하면 인수로 전달받은 에러를 발생시키고 `{value: undefined, done: true}`의 값을 반환한다.

<br/>

## 46.4 제너레이터의 일시 중지와 재개

제너레이터 함수는 일반 함수처럼 한 번에 코드 블록의 모든 코드를 일괄 실행하는 것이 아니라 yield 표현식까지만 실행한다. **yield 키워드는 제너레이터 함수의 실행을 일시 중지시키거나 yield 키워드 뒤에 오는 표현식의 평가 결과를 제너레이터 함수 호출자에게 반환한다.**
`next` 메서드와 `yield `표현식을 통해 함수 호출자와 함수의 `상태`를 주고받을 수 있고 함수 호출자는 next 메서드를 통해 yield 표현식까지 함수를 실행시켜 제너레이터 객체가 관리하는 상태를 꺼내올 수 있고 next 메서드에 인수를 전달해서 제너레이터 객체에 상태를 밀어넣을 수 있다.  
이러한 제너레이터 특성을 활용하면 비동기 처리를 동기 처리처럼 구현할 수 있다.

<br/>

## 46.5 제너레이터의 활용

### 46.5.1 이터러블의 구현

제너레이터 함수를 사용하면 이터레이션 프로토콜을 준수해 이터러블을 생성하는 방식보다 간단히 이터러블을 구현할 수 있다.

<br/>

### 46.5.2 비동기 처리

제너레이터 함수는 next 메서드와 yield 표현식을 통해 함수 호출자와 함수의 상태를 주고 받을 수 있다. 이러한 특성을 활용하면 프로미스를 사용한 비동기 처리를 동기 처리처럼 구현할 수 있다.  
다시 말해, 프로미스 후속 처리 메서드 try/catch/finally 없이 비동기 처리 결과를 반환하도록 구현할 수 있다.

```
const { response } = require('express');
const fetch = require('node-fetch');

const async = generatorFunc => {
    const generator = generatorFunc();✔️ (2)

    const onResolved = arg => {
        const result = generator.next(arg); ✔️ (5)

        return result.done
            ?result.value :
            result.value.then(res => onResolved(res)); ✔️ (7)

    }
    return onResolved; ✔️ (3)
}

(async(function * fetchTodo(){ ✔️ (1)
    const url = 'https://jsonplaceholder.typicode.com/post/1';

    const res = yield fetch(url); ✔️ (6)
    const todo = yield response.json(); ✔️ (8)
    console.log(todo);
})())✔️ (4)
```

1. async 함수가 호출되면(1) 인수로 전달받은 제너레이터 함수 fetchTodo를 호출하여 제너레이터 객체 생성(2) onResolved 함수를 반환(3)한다. onResolved 함수는 상위 스코프의 generator 변수를 기억하는 클로저다. async 함수가 반환한 onResolved 함수를 즉시 호출(4)하여 (2)에서 생성한 제너레이터 객체의 next 메서드를 처음 호출한다.(5)
2. next 메서드가 처음 호출(5)되면 제너레이터 함수 fetchTodo의 첫 번쨰 yield문(6)이 실행된다. 이때 next 메서드가 반환한 이터레이터 리절트 객체의 done 프로퍼티 값이 flase여서 이터레이터 리절트 객체의 value 프로퍼티 값, 즉 첫번쨰 yield된 fetch 함수가 반환한 프로미스가 resolve한 Response객체를 onResolved 함수에 인수로 전달하면서 재귀 호출(7)한다.
3. onResolved 함수에 인수로 전달된 Response 객체를 next 메서드에 인수로 전달하면서 next메서드를 두번째로 호출(5)한다. 이떄 next메서드에 인수로 전달한 Response 객체는 제너레이터 함수 fetchTodo의 response변수(6)에 할당되고 제너레이터 함수 fetchTodo의 두 번째 yield문(8)이 실행된다.
4. next 메서드가 반환한 이터레이터 리절트 객체의 done 프로퍼티 값이 false이므로 다시 재귀호출(7)한다.
5. onResolved 함수에 인수로 전달된 todo 객체를 next 메서드에 인수로 전달하면서 next 메서드를 세 번째로 호출(5)한다. 이때 next 메서드에 인수로 전달한 todo 객체는 제너레이터 함수 fetchTodo의 todo 변수에 할당(8)되고 제너레이터 함수 fetchTodo가 끝까지 실행된다.
6. next메서드가 반환한 이터레이터 리절트 객체의 done 프로퍼티 값이 true => 제너레이터 함수가 끝까지 실행되었다면 이터레이터 리전트 객체의 value 프로퍼티 값, 즉 제너레이터 함수의 반환값인 undefined를 그대로 반환(9)하고 처리를 종료한다.

<br/>

## 46.6 async/await

제너레이터를 사용해 비동기 처리를 동기 처리처럼 동작하도록 하였지만 코드가 장황해지고 가독성도 나빠진다. ES8에서는 제너레이터보다 간단하고 가독성 좋게 비동기 처리를 동기 처리처럼 동작하도록 구현할 수 있는 async/await이 도입되었다.

<br/>

async/await는 프로미스 기반으로 동작한다. 이것을 사용하면 프로미스의 후속 처리 메서드에 콜백 함수를 전달해서 비동기 처리 결과를 후혹 처리할 필요 없이 마치 동기 처리처럼 프로미스를 사용할 수 있다.

```
const fetch = require('node-fetch');
async function fetchTodo(){
    const url = 'https://jsonplaceholder.typicode.com/todos/1';

    const response = await fetch(url);
    const todo = await response.json();
    console.log(todo);
}
fetchTodo();
```

<br/>

### 46.6.1 async 함수

`await` 키워드는 반드시 `async 함수 내부`에서 사용해야 한다. async 함수는 언제나 프로미스를 반환한다. 명시적으로 프로미스를 반환하지 않더라도 암묵적으로 반환값을 resolve하는 프로미스를 반환한다.  
`클래스의 constructor` 메서드는 async 메서드가 될 수 없다. 클래스의 constructor 메서드는 `인스턴스`를 반환해야 하지만 `async` 함수는 언제나 `프로미스`를 반환해야 하기 때문이다.

<br/>

### 46.6.2 await 키워드

await 키워드는 프로미스가 settled상태(비동기 처리가 수행된 상태)가 될 때 까지 대기하다가 settled상태가 되면 프로미스가 resolve한 처리 결과를 반환한다. await 키워드는 반드시 프로미스 앞에서 사용해야 한다.

```
async function foo(){
    const a = await new Promise(resolve => setTimeout(()=> resolve(1),3000));
    const b = await new Promise(resolve => setTimeout(()=> resolve(2),2000));
    const c = await new Promise(resolve => setTimeout(()=> resolve(3),1000));

    console.log([a,b,c]); //[1,2,3]
}
foo(); // 약 6초 소요됨
```

위의 예제는 서로 연관 없이 개별적으로 수행되는 비동기 처리이므로 앞선 비동기 처리가 완료될 때까지 대기해서 순차적으로 처리할 필요가 없다. 이럴때는 Promise.all을 사용한다.

```
async function foo(){
    const res = await Promise.all([
        new Promise(resolve => setTimeout(()=> resolve(1),3000)),
        new Promise(resolve => setTimeout(()=> resolve(2),2000)),
        new Promise(resolve => setTimeout(()=> resolve(3),1000))
    ]);
    console.log(res); //[1,2,3]
}
foo(); //약 3초 소요
```

<br/>

### 46.6.3 에러 처리

비동기 처리를 위한 콜백 패턴의 단점 중 가장 심각한 것은 에러 처리가 곤란하다는 것이다. 에러는 호출자 방향으로 전파된다. 즉, 콜 스택의 아래 방향(실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향)으로 전파된다. 하지만 비동기 함수의 콜백 함수를 호출한 것은 비동기 함수가 아니기 때문에 try...catch문을 사용해 에러를 캐치할 수 없다.
<br/>

`async/await` 에서 에러 처리는 **try...catch 문을 사용할 수 있다.** 콜백 함수를 인수로 잔달받는 비동기 함수와는 달리 프로미스를 반환하는 비동기 함수는 명시적으로 호출할 수 있기 때문에 **호출자가 명확하다.**

```
const foo = async () =>{
    try{
        ~~
    }catch(err){
        console.error(err); //TypeError
    }
}
foo();
```

<br/>

async 함수 내에서 catch문을 사용해서 에러 처리를 하지 않으면 async 함수는 발생한 에러를 reject하는 프로미스를 반환한다. 따라서 catch문을 이용해 후속 처리 메서드를 사용해서도 에러를 캐치할 수 있다.

```
const foo = async () =>{
    const wrongUrl = '';
    const response = await fetch(wrongUrl);
    const data = await response.json();
    return data;
}
foo().then(console.log).chatch(console.error);//TypeError
```
